one_word/game_py/routes.py
from flask import render_template, redirect,flash,url_for,Blueprint
from flask_login import current_user,login_required
from one_word.models import ChatRoom,User,Message,StoryPost
from one_word import db,socket,app
from flask_socketio import emit,join_room,leave_room
import random
import string

game = Blueprint('game',__name__)

@game.route("/test")
def test():
    return render_template("test.html")
@socket.on("test")
def tester(data):
    c = ChatRoom.query.filter_by(id=current_user.chatroom_id).first()
    app.logger.warning(c.code==data['room'])
    join_room(data["room"])
    emit("warn",data['message'],room=data['room'])
    emit("test",data["message"],room=data["room"])

@game.route('/room_lobby')
def room_lobby():
    rooms = ChatRoom.query.all()
    return render_template('room_lobby.html',rooms=rooms)


@game.route('/game_room/<room_id>')
@login_required
def game_room(room_id):
    room = ChatRoom.query.filter_by(id=room_id).first()
    return render_template('game_room.html',room=room)

# @game.route('/create_room')
# @login_required
# def create_room():
#     if current_user.chatroom_id != None:
#         existing_room = current_user.chatroom_id
#         room = ChatRoom.query.filter_by(id=existing_room).first()
#         flash(f'You are already in a room ( {room.code} ). Please leave it to create another one.','danger')
#         return redirect(url_for('game.room_lobby'))
#     else:
#         new_room_code = generate_unique_code()
#         new_room = ChatRoom(host=current_user.id,code=new_room_code)
#         db.session.add(new_room)
#         db.session.commit()
#         current_user.chatroom_id = new_room.id
#         db.session.commit()
#     return redirect(url_for('game.game_room',room_id=new_room.id))

@socket.on('createRoom')
def create_room():
    if current_user.chatroom_id != None:
        existing_room = current_user.chatroom_id
        room = ChatRoom.query.filter_by(id=existing_room).first()
        emit('warn',f'You are already in a room ( {room.code} ). Please leave it to create another one.')
    else:
        new_room_code = generate_unique_code()
        new_room = ChatRoom(host=current_user.id,code=new_room_code,turn=current_user.id)
        db.session.add(new_room)
        db.session.commit()
        current_user.chatroom_id = new_room.id
        db.session.commit()
        emit('redirect',url_for('game.game_room',room_id=new_room.id))
    
@socket.on('joinRoom')
def joinRoom(chatroom_code):
    chatroom = ChatRoom.query.filter_by(code=chatroom_code).first()
    existing_room = ChatRoom.query.filter_by(id=current_user.chatroom_id).first()
    if chatroom:
        room =chatroom.code
        if existing_room:
            if existing_room.code != chatroom.code:
                emit('warn',f'You are already in another room ( #{existing_room.code} ). Please leave it to join room #{chatroom_code}.')
            elif existing_room.code == chatroom.code:
                members_data = []
                for member in chatroom.members:
                    is_host= True if member.id == chatroom.host else False
                    members_data.append({
                        "member_id":member.id,
                        "username":member.username,
                        "host":is_host})

                emit('updateConnected',members_data,room=room)
                emit('redirect',url_for('game.game_room',room_id=chatroom.id))
        elif not existing_room:
            current_user.chatroom_id = chatroom.id
            db.session.commit()

            members_data = []
            for member in chatroom.members:
                is_host= True if member.id == chatroom.host else False
                members_data.append({
                    "member_id":member.id,
                    "username":member.username,
                    "host":is_host})

            emit('updateConnected',members_data,room=room)
            emit('redirect',url_for('game.game_room',room_id=chatroom.id))

    elif not chatroom:
        emit('warn',f'Room does not exist anymore.')
        emit('redirect',url_for('game.room_lobby'))

# # @game.route('/delete_room/<room_id>')
# # def delete_room(room_id):
# #     if ChatRoom.query.filter_by(id=room_id).first():
# #         ChatRoom.query.filter_by(id=room_id).delete()
# #         chatroom_member = User.query.filter_by(chatroom_id=room_id).first()
# #         if chatroom_member:
# #             chatroom_member.chatroom_id = None
# #         db.session.commit()
# #         flash("Room deleted.",'success')
# #         return redirect(url_for('game.room_lobby'))

def generate_unique_code():
    times_checked = 0
    while True:
        # Generate a 4-character code
        code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=4))
        chatroom_code = ChatRoom.query.filter_by(code=code).first()
        if not chatroom_code:
            return code
        times_checked += 1
        if times_checked == 10:
            raise TimeoutError('Could not generate room code')
        
@socket.on("sendMessage")
def send_message(data):
    chatroom = ChatRoom.query.filter_by(code=data["room_code"]).first()
    app.logger.warning(chatroom.members)
    room = data["room_code"]
    user_id = int(data["user_id"])
    if user_id == chatroom.turn:
        if len((data["input_value"]).split()) > 1:
            emit('warn',"One word only, please.")
        else:
            #submit message and update turn
            msg = Message(message=data["input_value"],user_id=current_user.id,chatroom_id=current_user.chatroom_id)
            next_turn = 0
            members = chatroom.members
            for i in range(len(members)):
                if members[i].id == chatroom.turn:
                    next_turn = i + 1 if i + 1 < len(members) else 0
            chatroom.turn = members[next_turn].id
            db.session.add(msg)
            db.session.commit()
            username = members[next_turn].username
            message_data = {"message":msg.message,"user_id":msg.user_id,"next_turn":username}

            # emit("warn",'hi :D',room=room)
            emit("sendMessage",message_data,room=room)
    elif user_id != chatroom.turn:
        emit("warn","It's not your turn!")

@socket.on('connect')
def connect():
    if current_user.is_authenticated:
        chatroom = ChatRoom.query.filter_by(id=current_user.chatroom_id).first()
        if chatroom:
            room = chatroom.code
            join_room(room)

@socket.on("leave")
def leave():
    user = User.query.filter_by(id=current_user.id).first()
    chatroom = ChatRoom.query.filter_by(id=user.chatroom_id).first()
    leave_room(chatroom.code)
    if current_user.chatroom_id:
        current_user.chatroom_id = None
        db.session.commit()

    if chatroom.members:
        members = chatroom.members
        if current_user.id == chatroom.host:
            chatroom.host = [member.id for member in members][0]

            next_turn = 0
            for i in range(len(members)):
                if members[i].id == current_user.id:
                    next_turn = i + 1 if i < len(members) else 0
            chatroom.turn = members[next_turn].id
            db.session.commit()
        members_data = []
        for member in chatroom.members:
            is_host= True if member.id == chatroom.host else False
            members_data.append({
                "member_id":member.id,
                "username":member.username,
                "host":is_host})

        emit('updateConnected',members_data,room=chatroom.code)
        emit("warn",f'{user.username} has left.',room=chatroom.code,include_self=False)
        emit("redirect",url_for('game.room_lobby'))

    if not chatroom.members:
       ChatRoom.query.filter_by(id=chatroom.id).delete()
       Message.query.filter_by(chatroom_id=chatroom.id).delete()
       db.session.commit()
       emit("redirect",url_for('game.room_lobby'))

@game.route("/submit_story/<room_id>")
def submit_story(room_id):
    room = ChatRoom.query.filter_by(id=int(room_id)).first()
    members = [member.username for member in room.members]
    msg = [message.message for message in room.messages]
    app.logger.warning(msg)
    if msg:
        story = " ".join(msg)
        authors = " ".join(members)
        new_story = StoryPost(story=story,authors=authors)
        db.session.add(new_story)
        db.session.delete(room)
        db.session.commit()
        return redirect(url_for('main.read_stories'))
    

one_word/main_py/routes.py
from flask import render_template,Blueprint
from one_word.models import User,StoryPost
main = Blueprint('main',__name__)

@main.route('/')
def home():
    users = User.query.all()
    return render_template('home.html',users=users)

@main.route('/read_stories')
def read_stories():
    stories = StoryPost.query.all()
    return render_template('stories.html',stories=stories)

# @main.route('/test')
# def test():
#     return render_template('test.html')

one_word/userAuth_py/routes.py
from flask import render_template, redirect,flash,url_for,Blueprint,request
from flask_login import current_user,login_user,logout_user
from one_word.forms import SignupForm, LoginForm
from one_word.models import User
from one_word import db,bcrypt
users = Blueprint('users',__name__)

@users.route('/signup',methods=['GET', 'POST'])
def signup():
    """
    Users register their account.
    """
    form = SignupForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,email=form.email.data,password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created.','success')
        return redirect(url_for('users.login'))
    return render_template('signup.html',form=form,title='Sign Up')

@users.route('/login',methods=['GET', 'POST'])
def login():
    """
    User logs in.
    """
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            flash(f'Welcome, {user.username}!','success')
            return redirect(next_page) if next_page else redirect(url_for('game.room_lobby'))
        else:
            flash('Login unsuccessful. Please check email and password.','danger')
    return render_template('login.html',form=form,title='Login')

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

one_word/templates/game_room.html
{% extends 'socket_layout.html' %}
{% block content %}    
<section>
  <div class="content-container">
      <!-- Left Fat Box -->
      <div class="fat-box">
        <div class="fat-box-info">
            <small>Room #{{room.code}}</small>
            {% for member in room.members %}
              {% if member.id == room.turn %}  
                <h3><i class="member-turn">{{member.username}}'s turn!</i></h3>
              {% else %}
              {% endif %}
            {% endfor %}
        </div>
        <!-- <h1 class="title">Tales of the Seven NineTales</h1> -->
          <div class="messages">
              {% for value in room.messages %}
                <span id="{{value.user_id}}" class="message">{{value.message}}</span>
              {% endfor %}
          </div>
        <div class="message-container"><input class="message-input" onkeyup="enterMessage('{{room.id}}','{{room.code}}','{{current_user.id}}')"><button class="message-button" onclick="sendMessage('{{room.id}}','{{room.code}}','{{current_user.id}}')">Send</button></div>
      </div>
      <!-- Right Two Small Boxes -->
      <div class="small-boxes">
          <div class="small-box">
              <h2>Group</h2>
            {% for member in room.members %}
              {% if member.id == room.host %}
                <div class="member" id="{{member.id}}" onmouseover="highlight()">
                  <!-- <img src="{{url_for('static', filename='profile.png')}}" alt="Group member photo icon" class="member-icon"> -->
                  <span>{{member.username}} &lpar;Host&rpar;</span>
                </div>
              {%else%}
                <div class="member" id="{{member.id}}" onmouseover="highlight()">
                  <!-- <img src="{{url_for('static', filename='profile.png')}}" alt="Group member photo icon" class="member-icon"> -->
                  <span>{{member.username}}</span>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <div class="small-box">
            <h2>Voting Calls</h2>
            <small>Coming soon...</small>
            <p>Kick a Member</p>
            <p>Create a Title</p>
            <p>Start a New Paragraph</p>
            <p>Nudge a Player</p>
            <small>Use:</small>
            <a href="{{url_for('game.submit_story', room_id=room.id)}}"><p>Submit Story</p></a>
            <a onclick="leaveRoom('{{current_user.id}}')"><p>Leave Room</p></a> 
          </div>
      </div>
  </div>
</section>
{% endblock %}

one_word/templates/home.html
{% extends 'layout.html' %}
{% block content %}        
<section class="landing">
   <div class="landing-container">
     <div style="padding:10px;"><small>Currently {{users | length }} players</small></div>
     <a href="#" class="button">Beta Version</a>
      <h1>The One-Word Story Online Game</h1>
      <p>One person says a single word to begin a story. The next person says another 
       word, then the next person says another word, and so on, in circles, within the 
       group. The object is to tell a coherent story, one word at a time.
      </p>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/nPN6OHBIcsc?si=1tTwGl06mIxEhu9P" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
   </div>
 </section>

 <section>
   <div class="how-it-works">
       <div style="min-width:550px;">
           <h2>How it Works</h2>
           <h3>Sign Up/Login</h3>
           <p>Create an account or log in to play! No need to download anything.</p>
           <h3>Find/Join Rooms</h3>
           <p>Browse through available rooms or create your own to invite friends, family, and other players to join in the fun.</p>
           <h3>Post Stories</h3>
           <p>Share your creative story with the community and explore others' tales. Discover new perspectives and engage in meaningful storytelling experiences.</p>
           {% if current_user.is_authenticated %}
           <a href="{{url_for('game.room_lobby')}}" class="button">Play</a>
           {% else %}
           <a href="{{url_for('users.signup')}}" class="button">Sign up & Play</a>
            
           {% endif %}
       </div>
       <img src="{{url_for('static', filename='chatroom.png')}}" alt="Interactive storytelling session with multiple participants engaging." style="width: 50%; height: 100%;">
   </div>
 </section>
{% endblock %}

one_word/templates/layout.html
<!DOCTYPE html>
<html lang="en">
 <head>  
   <meta charset="UTF-8" />
   <meta name="viewport" content="width=device-width" />
   <title>Landing Page</title>
   <!--google font-->
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<!--css-->
<link href="{{url_for('static', filename='styles.css')}}" rel="stylesheet">
<!--google analytics-->
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-N3N0K6SHZN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-N3N0K6SHZN');
</script>
</head>
 <body> 
    <nav>
       <a>Rate</a>
       <a href="{{url_for('main.read_stories')}}">Read</a>
       <a href="{{url_for('main.home')}}">Home</a>
       <a href="{{url_for('game.room_lobby')}}">Play</a>
      {% if current_user.is_authenticated %}
         
      <a href="{{url_for('users.logout')}}">Log Out</a>
      {% else %}
         
      <a href="{{url_for('users.signup')}}">Signup</a>
      <a href="{{url_for('users.login')}}">Login</a>
      {% endif %}
     </nav>
      {% with messages = get_flashed_messages(with_categories=true) %}
               {% if messages %}
                   {% for category, message in messages %}
                       <div style="padding:5px;margin:10px;"><small class={{category}}>{{message}}</small></div>
                   {% endfor %}
               {% endif %}
           {% endwith %}
           <style>
               .socket-broadcast {padding:5px;margin:10px;position:fixed; top:7%;left:5%;}
           </style>
           <div class="socket-broadcast"><small></small></div>
    {% block content %}
    {% endblock %}
</body>
</html>

one_word/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<section class="signup-section">
    <div class="signup-container">
      <h2>Log In</h2>
      <form class="signup-form" method="POST" action="" novalidate>
        {{form.hidden_tag()}}
        
        <div class="input-container">
          {{form.email.label}}
          {{form.email(class_='signup-input')}}
          {% if form.email.errors %}
              {% for error in form.email.errors %}
                  <small class="danger">{{error}}</small> 
              {% endfor %}
          {% endif %}
        </div>
        
        <div class="input-container">
          {{form.password.label}}
          {{form.password(class_='signup-input')}}
          {% if form.password.errors %}
                  {% for error in form.password.errors %}
                      <small class="danger">{{error}}</small>
                  {% endfor %}
              {% endif %}
        </div>
      
        {{form.submit(class_='signup-button')}}
    </form>
      <p class="signup-or">Or</p>
      <div class="signup-social-container">
        <button class="signup-social-button">
          <img src="{{url_for('static', filename='google.png')}}" alt="Google" class="signup-social-icon">
          Sign in with Google
        </button>
        <button class="signup-social-button">
          <img src="{{url_for('static', filename='apple.png')}}" alt="Apple" class="signup-social-icon">
          Sign in with Apple
        </button>
      </div>
    </div>
  </section>
{% endblock %}

one_word/templates/room_lobby.html
{% extends 'socket_layout.html' %}
{% block content %}
<section  class="chatroom-container">
    <div class="chatroom-inner-container">
        <h1>Chat Rooms</h1>
        <input type="search" class="search-input" placeholder="Search for rooms...">
         <!-- New container -->
        <div class="room-inner-container">
            <h2>Create Chat Room</h2>
            <p>Begin an exciting story adventure of your own.</p>
            {% if current_user.is_authenticated %}    
                <a onclick="createRoom()"><button class="create-button">CREATE NOW</button></a>
            {% else %}
                <a href="{{url_for('users.login')}}"><button class='create-button'>SIGN IN TO CREATE NOW</button></a>
            {% endif %}
        </div>
        {% for room in rooms %}    
        <div class="room-inner-container">
            <h2>
                <!--Put title here in future-->
                Members:
                {% for member in room.members %}
                    {{member.username}}
                {% endfor %}
            </h2>
            <h4>ROOM {{room.code}} ({{room.members|length}} members)</h4>
            <p>
                {% if room.messages | length < 45 %}
                    {% for message in room.messages %}
                        {{message.message}}
                    {% endfor %}
                {% else %}
                    {% for message in range(45) %}
                        {{message.message}}
                    {% endfor %}...
                {% endif %}
            </p>
            {% if current_user.is_authenticated %}
                
            <a onclick="joinRoom('{{ room.code }}') "><button class="create-button">JOIN</button></a>
            {% else %}                
            <a href="{{url_for('users.login')}}"><button class="create-button">SIGN IN TO JOIN</button></a>
            {% endif %}

        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

one_word/templates/signup.html
{% extends 'layout.html' %}
{% block content %}  
<section class="signup-section">
  <div class="signup-container">
    <h2>Write Stories Now.</h2>
      <form class="signup-form" method="POST" action="" novalidate>
          {{form.hidden_tag()}}
          
          <div class="input-container">
            {{form.username.label}}
            {{form.username(class_='signup-input')}}
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <small class="danger">{{error}}</small>
                {% endfor %}
            {% endif %}
          </div>
          
          <div class="input-container">
            {{form.email.label}}
            {{form.email(class_='signup-input')}}
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                    <small class="danger">{{error}}</small> 
                {% endfor %}
            {% endif %}
          </div>
          
          <div class="input-container">
            {{form.password.label}}
            {{form.password(class_='signup-input')}}
            {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <small class="danger">{{error}}</small>
                    {% endfor %}
                {% endif %}
          </div>
          <div class="input-container">
            {{form.confirm_password.label}}
            {{form.confirm_password(class_='signup-input')}}
            {% if form.confirm_password.errors %}
                {% for error in form.confirm_password.errors %}
                    <small class="danger">{{error}}</small>
                {% endfor %}
            {% endif %}
          </div>
          
          {{form.submit(class_='signup-button')}}
      </form>
    <p class="signup-or">Or</p>
    <div class="signup-social-container">
      <button class="signup-social-button">
        <img src="{{url_for('static', filename='google.png')}}" alt="Google" class="signup-social-icon">
        Sign in with Google
      </button>
      <button class="signup-social-button">
        <img src="{{url_for('static', filename='apple.png')}}" alt="Apple" class="signup-social-icon">
        Sign in with Apple
      </button>
    </div>
    <p class="signup-account">Have an account? <a href="#" class="signup-link">Sign in</a></p>
  </div>
</section>
<div class="signup-container">
  
</div>
{% endblock %}

one_word/templates/socket_layout.html
<!DOCTYPE html>
<html lang="en">
 <head>  
   <meta charset="UTF-8" />
   <meta name="viewport" content="width=device-width" />
   <title>One Word Story Online Game</title>
   <!--google font-->
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<!--socket cdn-->
<script src="https://cdn.socket.io/4.7.5/socket.io.min.js" integrity="sha384-2huaZvOR9iDzHqslqwpR87isEmrfxqyWOF7hr7BY6KG0+hVKLoEXMPUJw3ynWuhO" crossorigin="anonymous"></script>
<!--css-->
<link href="{{url_for('static', filename='styles.css')}}" rel="stylesheet">
<!--socket.js-->
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-N3N0K6SHZN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-N3N0K6SHZN');
</script>
</head>
 <body> 
    <nav>
        <a>Rate</a>
        <a href="{{url_for('main.read_stories')}}">Read</a>
        <a href="{{url_for('main.home')}}">Home</a>
        <a href="{{url_for('game.room_lobby')}}">Play</a>
        {% if current_user.is_authenticated %}
            
        <a href="{{url_for('users.logout')}}">Log Out</a>
        {% else %}
            
        <a href="{{url_for('users.signup')}}">Signup</a>
        <a href="{{url_for('users.login')}}">Login</a>
        {% endif %}
 
    </nav>
      {% with messages = get_flashed_messages(with_categories=true) %}
               {% if messages %}
                   {% for category, message in messages %}
                       <div style="padding:5px;margin:10px;"><small class={{category}}>{{message}}</small></div>
                   {% endfor %}
               {% endif %}
           {% endwith %}
           <style>
               .socket-broadcast {padding:5px;margin:10px;position:fixed; top:7%;left:5%;}
           </style>
           <div class="socket-broadcast"><small></small></div>
    {% block content %}
    {% endblock %}
    <script src="{{url_for('static', filename='socket.js')}}" defer></script>
</body>
</html>

one_word/templates/stories.html
{% extends 'layout.html' %}
{% block content %}
<section  class="chatroom-container">
    <div class="chatroom-inner-container">
        <h1>Stories</h1>
        <input type="search" class="search-input" placeholder="Search for rooms...">
         <!-- New container -->
        {% for a_story in stories %}    
        <div class="room-inner-container">
            <h2>
            </h2>
            <h4>{{a_story.authors}}</h4>
            <p>
                {{a_story.story}}
              
            </p>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

one_word/templates/test.html
{% extends 'socket_layout.html' %}
{% block content %}
    <p class="dash">something</p>
    <input class="massage">
    <input class="rm">
    <button onclick="test()">test</button>
{% endblock %}